name = "seraapp"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "seraapp"
database_id = "85fd29b3-4366-4cd0-8975-47b44473e99d"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "SESSIONS"
id = "5b67d7075d404691a00e68d7b669ea5e"
